### ISSUE TITLE
Does not accept "orig" as a size

### ISSUE THREAD

**Issue by Slessi** [Michigan-Tech-Courses/thumbor#1]
According to thumbor docs https://thumbor.readthedocs.io/en/latest/usage.html#image-size
It should be possible to use `"orig"` as a size parameter.

> If you specify one of the dimensions as the string “orig” (as in 𝑜𝑟𝑖𝑔𝑥100, 100𝑥𝑜𝑟𝑖𝑔, 𝑜𝑟𝑖𝑔𝑥𝑜𝑟𝑖𝑔), thumbor will interpret that you want that dimension to remain the same as in the original image.

```ts
// Argument of type 'number | "orig"' is not assignable to parameter of type 'number'.
// Type 'string' is not assignable to type 'number'.ts(2345)
thumbor.setPath(path).resize(width, height).buildURL();
```

**Comment by codetheweb** [comment]
Fixed and published in v1.0.2.
