### ISSUE TITLE
Size is missing from URL when using both with width & height 0

### ISSUE THREAD

**Issue by Slessi** [Michigan-Tech-Courses/thumbor#2]
According to thumbor docs https://thumbor.readthedocs.io/en/latest/usage.html#image-size
It should be possible to use `"0x0"` as a size parameter.

> If you use 0𝑥0, Thumbor will use the original size of the image and thus won’t do any cropping or resizing.

```ts
thumbor.setPath(path).resize(0, 1).buildURL(); // https://cdn/secret/0x1/image.jpg
thumbor.setPath(path).resize(1, 0).buildURL(); // https://cdn/secret/1x0/image.jpg
thumbor.setPath(path).resize(0, 0).buildURL(); // https://cdn/secret//image.jpg -- Size is missing
```

**Comment by codetheweb** [comment]
Thanks for the report; fixed in v1.0.3. Note that this is now the default behavior as well (i.e `thumbor.setPath(path).buildURL() -> https://cdn/secret/0x0/image.jpg`).
